version: '3.9'

services:
  training_db:
    image: postgres:15-bullseye
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - 6500:5432
    networks:
      - training_net
    deploy:  
      resources:
        limits:
          cpus: '0.2'
          memory: 300M

  training:
    build: .
    environment:
      GUNICORN: false
    volumes:
      - .:/usr/app
    ports:
      - 6550:80
    networks:
      - training_net
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 300M
    depends_on:
      training_db:
        condition: service_started

networks:
  training_net:
    driver: bridge
    name: training_net