kind: Service
apiVersion: v1
metadata:
  name: service-training-plan
  annotations:
    cloud.google.com/backend-config: '{"default": "training-plan-config"}'
spec:
  type: NodePort
  selector:
    app: training-plan
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31025